### ISSUE TITLE
Not checking for openings by Advisor

### ISSUE THREAD

**Issue by jadedtdt** [emanguy/CMSC331-Project2#12]
I just found out out that if Advisor X has an appointment at 9:00 and Advisor Y does not, the program does not currently check appointment calendars based on advisor name, only times. This needs to be fixed. Not sure if important to fix now or wait until we rework our DB setup?

**Comment by emanguy** [comment]
Which files are affected by this? I can take a look into it if you want.

**Comment by jadedtdt** [comment]
Results3.php I believe. I will try to add better naming schemes for the files later

**Comment by emanguy** [comment]
Is this issue fixed after our modifications to the design of Results1? Should we close this as of pull request #23?

**Comment by jadedtdt** [comment]
I don't know, it should, but I will need to test tomorrow. Let's leave this open until it's confirmed fixed.

**Comment by emanguy** [comment]
Is this a duplicate of #21?

**Comment by jadedtdt** [comment]
This issue has to do with grabbing available appointment times. The other issue has to do with displaying the advisors for selected majors.

**Comment by emanguy** [comment]
:+1:

**Comment by emanguy** [comment]
Again is this fixed due to #34?

**Comment by jadedtdt** [comment]
yes
