### ISSUE TITLE
Doesn't NULL check the $chkbGroup or $chkbIndividual

### ISSUE THREAD

**Issue by jadedtdt** [emanguy/CMSC331-Project2#13]
so if none of the checkboxes for individual or group are checked, NULL is store into the respective objects but the code does not account for the chance of there being a NULL. The easy fix is just to add if ($chkbGroup != null)
...

etc

**Comment by emanguy** [comment]
As an addon to this issue, we also need to null check the advisors-- it's possible to just not select group/individual advising for ANYTHING and then get a blank page once you hit "go" from Results1. I'll try to fix that later today.

EDIT: made an offshoot issue #15

**Comment by jadedtdt** [comment]
@emanguy This also occurs in Results3.php

**Comment by emanguy** [comment]
I propose we just remove the checkboxes in Results2 altogether. Why not just display the date picker and label ONLY if it was checked on Results1? Is there a UI design purpose for this? Clicking unchecked checkboxes only seems to complicate things more as well.

**Comment by jadedtdt** [comment]
So the initial thought was if the student changed his/her mind, the decision to only include individual appointments could be expanded back to group appointments without navigating backwards. I think it would be easier on everyone if the checkboxes were just removed as you proposed.

**Comment by emanguy** [comment]
Okay sounds good, I'll incude the change in my next commit to pull request #16 .
