### ISSUE TITLE
Add page to remove advisors if necessary

### ISSUE THREAD

**Issue by emanguy** [emanguy/CMSC331-Project2#18]
According to the [Project 2 Requirements](https://docs.google.com/viewer?url=http%3A%2F%2Fuserpages.umbc.edu%2F~slupoli%2Fnotes%2FProgLanguages%2Fprojects%2FUMBCUndergradAdvising%2FCMSC%2520UMBC%2520Undergrad%2520Advising%2520Project%2520-%2520Part%25202.docx), we need to give the student the ability to remove appointments they've signed up for.

My proposed changes include:
- Modify the DB so assigned appointments get saved (we need to have design talks on this)
- Add a new page, perhaps RemoveAppointment.php, which allows the student to see appointments they have and delete ones they don't want.
- Add a link to the nav bar at the top of the page that links to RemoveAppointment.php or whatever we decide to call it.
- Do validation to determine if the student has registered for anything already and display an error message when they don't. Perhaps provide a link to index.php when no appointments exist? Could be redundant given the nav bar at the top.
- Perhaps add a function in Utilities.php to show advising times, we may be able to reuse it when we show the advising appointments to advisors later on.

We may need to assign multiple people to this.

**Comment by jadedtdt** [comment]
I feel all of those should be implemented after the DB setup is finalized.

**Comment by emanguy** [comment]
This is fixed as of pull request #24.
