### ISSUE TITLE
Modify Results3 to support additional tables

### ISSUE THREAD

**Issue by emanguy** [emanguy/CMSC331-Project2#19]
I'll attach a google drive link to the new tables later.

**Comment by jadedtdt** [comment]
Okay

**Comment by emanguy** [comment]
@jadedtdt It was emailed to both you and @tbrandt1 , take a look

**Comment by jadedtdt** [comment]
okay I added a draft to the DB, either of you feel free to edit based on what's best appropriate!

**Comment by emanguy** [comment]
This is now assigned to @tbrandt1 because he was already working on the table enhancement for Results3.

**Comment by emanguy** [comment]
Fixed as of #34
