### ISSUE TITLE
Results2.php shows advisors when neither individual nor group box is checked

### ISSUE THREAD

**Issue by emanguy** [emanguy/CMSC331-Project2#20]
![glitch](https://cloud.githubusercontent.com/assets/6354401/7234295/197b1b7e-e754-11e4-8b6b-a06d3acfee17.png)
Note: neither the individual nor the group advising check box was checked for Carol's major.

**Comment by jadedtdt** [comment]
Not sure how you can progress to this page without selecting one given the fix for required-atleastoneappttype or whatever it was called

feel free to reopen if still an issue after i commit
