### ISSUE TITLE
Get list of advisors with no duplicates in Results1.php

### ISSUE THREAD

**Issue by emanguy** [emanguy/CMSC331-Project2#21]
We need to just list the advisors and their associated majors. See image below.
![updatedadvisorselect](https://cloud.githubusercontent.com/assets/6354401/7234666/a815bcf2-e756-11e4-844c-038ad77a2c1c.png)

**Comment by jadedtdt** [comment]
``` php
$counter = 0;
$sql = "select * from `Appointment` where `IsGroup` = '1' and `Time` LIKE '$date%'";
$rs = $COMMON-> executeQuery($sql, $_SERVER["SCRIPT_NAME"]);
$numRows = SELECT DISTINCT COUNT(*) `AppointmentID` FROM `Appointment` WHERE `IsGroup` = 1
while($row = mysql_fetch_array($rs)) {
    $timedateArr = $row['Time'];
    $timeDate = explode(" ", $timedateArr);
    $date = $timeDate[0];
    $time = $timeDate[1];
    $dbTimes[$counter] = $time;
    $counter++;
}

# Set up first part of query with first major choice
$advisorNames = "SELECT * FROM `Advisor` WHERE `Majors` LIKE '%$cbMajors[0]%'";

# Add additional major choices after the first one
for ($i = 1; $i < count($cbMajors); $i++)
{
    $advisorNames = ""$advisorNames" OR `Majors` LIKE '%$cbMajors[$i]%'"
}
```

**Comment by jadedtdt** [comment]
![](http://puu.sh/hmzbw/0cf68aed8d.png)
Current progress @emanguy, will take feedback

**Comment by emanguy** [comment]
Didn't you already finish writing the code to fix this issue? Should I close this?

**Comment by jadedtdt** [comment]
wait until i have time to commit to github

**Comment by emanguy** [comment]
Okay, sounds good. Keep up the good work Gene!

**Comment by jadedtdt** [comment]
So graphically this is fixed, just going to leave it open in case it creates complications in Results3 because I forsee an issue when trying to schedule an appointment for 2 majors with the same advisor (not sure how to be handled)

**Comment by emanguy** [comment]
@tbrandt1 just committed pull request #

**Comment by emanguy** [comment]
@tbrandt1 just added his Results3 changes. Do we close this?
