### ISSUE TITLE
RequiredAtLeastOne1 and RequiredAtLeastOne2?

### ISSUE THREAD

**Issue by jadedtdt** [emanguy/CMSC331-Project2#22]
We need to somehow check to make sure at least one advisor is checked

![](http://puu.sh/hmWhp/2ec1630dd4.png)

This can be found in Results2.php, will most likely require another version of the current implementation of requiredAtLeastOne.

**Comment by emanguy** [comment]
Code is written but Amtrak Wi-Fi doesn't let me push. I'll push my fix when I get home.

**Comment by emanguy** [comment]
Closing due to pull request #23
