### ISSUE TITLE
Add more return buttons?

### ISSUE THREAD

**Issue by jadedtdt** [emanguy/CMSC331-Project2#29]
In the advisor feedback, we were critiqued on not having return to home buttons. "Some navigational buttons would be useful, so that students don’t hit dead ends in the application. For example, the ‘Congratulations, Sign Up Successful’ page has no hyperlink back to the student portal."

I think that some of these should be in place of any pages that might include dead ends such as error pages, completion pages, or any others you guys might think of.

**Comment by emanguy** [comment]
Yep, I made sure to add return links in wherever I could in my code

**Comment by jadedtdt** [comment]
I also made sure to add them in my code
