### ISSUE TITLE
Change text in Footer.html

### ISSUE THREAD

**Issue by emanguy** [emanguy/CMSC331-Project2#8]
We should determine how to change the "contact Gene Burchette" bit in footer.html. Thoughts?

**Comment by jadedtdt** [comment]
I don't really care what we put here. It was just to look more professional in the individual project. Could be something along the lines of like opening a ticket for support? I'm very open to other ideas.

**Comment by emanguy** [comment]
I like the support ticket idea. Maybe we could also include a link to the
DoIT support ticket submission page. The only issue with that idea is that
I know the library kiosks don't allow you to visit websites outside the
original domain.
