### ISSUE TITLE
Separate Stylesheet

### ISSUE THREAD

**Issue by emanguy** [emanguy/CMSC331-Project2#9]
We shouldn't be redefining a style tag in every PHP file. We need to consolidate all of our styles in one external CSS sheet.

Remember that importing an external stylesheet is done using 

``` html
 <link rel="stylesheet" type="text/css" href="PATH_TO_STYLESHEET">
```

**Comment by jadedtdt** [comment]
I don't know how to do much in CSS. I'm probably going to assign this to you.
